server:
  port: 8001
dubbo:
  application:
    name: provider
  registry:
    #註冊中心地址
    address: zookeeper://192.168.56.101:2181
    timeout: 6000
  #元中心地址
  metadata-report:
    address: zookeeper://192.168.56.101:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.example.provider.service



